const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={home:'<path d="m3 10 9-7 9 7v10H3z"/><path d="M9 20v-7h6v7"/>',cases:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M8 5V3h8v2M3 11h18M10 11v3h4v-3"/>',resources:'<path d="M4 3h6a3 3 0 0 1 3 3v15a4 4 0 0 0-4-2H4zM13 6a3 3 0 0 1 3-3h5v16h-5a4 4 0 0 0-3 2"/>',analytics:'<path d="M4 3v18h18M9 16v-5M14 16V7M19 16v-9"/>',settings:'<path d="m10 3-1 3-3 1-3 3 2 3-1 3 3 2 3-1 2 3 3-1 1-3 3-1 2-3-2-3 1-3-3-2-3 1z"/><circle cx="12" cy="12" r="3"/>'};
const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">${icons[n]||icons.home}</svg>`;
const baseText='今天跟王伯伯聊天，他說以前常去公園下棋，覺得滿開心的。最近膝蓋偶爾不舒服，所以比較少出去。他說如果不是星期三，他願意再去一次，也希望不要太遠。';
let logged=false,route='home',caseTab='overview',resultTab='ai',caseFilter='全部',search='',resourceSearch='',filters={},onlySuggested=true,tracking=false,modal='',selectedResource=0,selectedCase=0,recordIndex=0;
let records=[{date:'2026/10/03',person:'林書含（物理治療師）',source:'現場訪談',summary:'談到過去下棋活動、近期外出與膝部不適。',status:'已參與活動',text:baseText},{date:'2026/09/27',person:'陳雅婷（社工）',source:'專案參與',summary:'表示有興趣先去看看附近活動，但擔心一個人不熟悉。',status:'考慮參與',text:'王伯伯表示有興趣先去看看附近活動，但擔心一個人不熟悉。希望先知道活動地點，也想詢問是否可以有人同行。'},{date:'2026/09/20',person:'林書含（物理治療師）',source:'現場訪談',summary:'跌倒後較少出門，以前喜歡去公園下棋，現在覺得不太敢。',status:'尚未參與',text:'王伯伯說跌倒後較少出門，以前喜歡去公園下棋，現在覺得不太敢。下次可詢問是否願意先由熟悉的人陪同。'},{date:'2026/09/10',person:'王志明（志工）',source:'家訪紀錄',summary:'日常生活大致可自理，女兒白天工作，平時獨居。',status:'生活良好',text:'家訪時王伯伯表示日常生活大致可自理，女兒白天工作，平時獨居。喜歡和鄰居聊天。'}];
let cases=[['王伯伯',78,'2026/10/03',2,'確認下次活動時間'],['林奶奶',82,'2026/09/28',7,'確認交通方式'],['陳伯伯',80,'2026/09/20',15,'尚無後續紀錄'],['張奶奶',85,'2026/09/10',25,'評估居家支持需求'],['李爺爺',79,'2026/08/28',36,'安排再次訪視'],['周奶奶',76,'2026/10/01',4,'確認陪同人選'],['黃伯伯',81,'2026/09/30',5,'詢問共餐意願'],['蔡奶奶',77,'2026/09/26',9,'追蹤手作活動感受'],['吳爺爺',83,'2026/09/24',11,'確認可參與時段'],['許奶奶',80,'2026/09/23',12,'確認交通安排'],['劉伯伯',75,'2026/09/15',20,'詢問活動偏好'],['趙奶奶',84,'2026/08/25',41,'安排電話關懷']];
const resources=[{name:'○○社區關懷據點－長者棋藝活動',short:'長者棋藝活動',tags:['下棋','社交','室內活動'],place:'臺中市西區 ○○里活動中心',day:'週二、週五',time:'14:00–16:00',traffic:'步行約 10 分鐘／公車可達',type:'棋藝',area:'西區',symbol:'♟',desc:'由據點志工協助安排棋友，歡迎先來看看，也可由熟悉的人陪同首次參與。'},{name:'○○社區共餐',short:'社區共餐',tags:['共餐','社交'],place:'臺中市西區 ○○社區食堂',day:'週一、週四',time:'11:30–13:00',traffic:'公車可達',type:'共餐',area:'西區',symbol:'♧',desc:'一起吃頓飯、聊聊生活。參加前需由工作人員確認報名與餐食安排。'},{name:'公園晨間健走團',short:'公園健走團',tags:['戶外','健走'],place:'臺中市南區 ○○公園',day:'週三',time:'08:00–09:00',traffic:'需接送',type:'健走',area:'南區',symbol:'↟',desc:'依個人意願與狀況選擇路線，參與前請確認交通與步行需求。'},{name:'社區生活手作課程',short:'手作課程',tags:['手作','室內活動'],place:'臺中市西區 ○○學習中心',day:'週六',time:'10:00–12:00',traffic:'公車可達',type:'手作',area:'西區',symbol:'✂',desc:'以簡單生活手作為主，材料由據點準備，可先詢問當週主題。'},{name:'一起唱歌・社區歌唱活動',short:'社區歌唱活動',tags:['歌唱','社交'],place:'臺中市北區 ○○活動中心',day:'週三',time:'14:00–16:00',traffic:'需接送',type:'歌唱',area:'北區',symbol:'♫',desc:'透過熟悉的歌曲與同伴交流，歡迎自由選擇聆聽或一起唱。'}];
const brand=()=>'<div class="brand"><img class="brand-icon" src="logo.svg" alt="" width="40" height="40">LinkAge</div>';
const btn=(text,action,style='')=>`<button class="btn ${style}" onclick="${action}">${text}</button>`;
const badge=(text,color='')=>`<span class="badge ${color}">${esc(text)}</span>`;
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',3200)}
function go(r){if(r==='home'||r==='cases')fromStat=false;if(r==='resources'&&route!=='resources'){filters={};resourceSearch=''}route=r;modal='';render();window.scrollTo(0,0)}
function openCase(i=0,tab='overview'){selectedCase=i;records=caseRecords[i]||(caseRecords[i]=[]);caseTab=tab;filters={};onlySuggested=i===0;go('case')}
function tab(t){if(t==='matching'&&caseTab!=='matching')filters={};caseTab=t;go('case')}
function viewRecord(i){recordIndex=i;resultTab='ai';go(records[i].feedback?'feedbackDetail':'result')}
const cname=()=>cases[selectedCase][0];
function crumb(parts=[]){return `<div class="crumb"><button onclick="go('cases')">個案管理</button><span>／</span><button onclick="openCase(${selectedCase})">${esc(cname())}</button>${parts.map(p=>`<span>／</span>${p[1]?`<button onclick="${p[1]}">${p[0]}</button>`:`<span>${p[0]}</span>`}`).join('')}</div>`}
function header(title,sub='',action=''){return `<div class="intro row between"><div><h1>${title}</h1>${sub?`<p>${sub}</p>`:''}</div>${action}</div>`}
function stats(labels,values,interactive=false){return `<div class="grid four">${labels.map((l,i)=>`${interactive?`<button type="button" class="card stat stat-link" onclick="openStat(${i})" aria-label="${l}，${values[i]}${i===0||i===1?'位':'筆'}，查看明細">`:'<div class="card stat">'}<span class="stat-label">${l}</span><div class="number">${values[i]}<small> ${i===0?'位':''}</small></div><span aria-hidden="true" class="stat-icon ${['','orange','green','pink'][i]}">${['♧','◷','✓','☷'][i]}</span><small>${['持續累積每一次理解','把關心化為下一步行動','連結社區，留下參與結果','下一次接觸時再確認'][i]}</small>${interactive?'<span class="stat-detail-link">查看明細</span></button>':'</div>'}`).join('')}</div>`}

function login(){return `<div class="login"><section class="login-story">${brand()}<div><span class="badge">CONNECT · UNDERSTAND · CARE</span><h1>每一次接觸，<br>都讓理解更靠近。</h1><p>把生活中的點滴串起來，<br>讓陪伴有脈絡，讓參與有可能。</p><div class="login-orbit"><div class="orbit-card"><strong>01</strong><h3>接觸</h3><span>記下每一次真實的交流</span></div><div class="orbit-card"><strong>02</strong><h3>理解</h3><span>看見一個人的生活脈絡</span></div><div class="orbit-card"><strong>03</strong><h3>連結</h3><span>一起找到參與的可能</span></div><div class="orbit-card"><strong>04</strong><h3>陪伴</h3><span>讓回饋成為下一次理解</span></div></div></div><small>為第一線服務人員而設計的陪伴工作平台</small></section><section class="login-form"><div class="login-form-inner">${brand()}<h2>長者社會參與與陪伴追蹤平台</h2><p>讓每一次接觸，都累積成對一個人的理解。</p><form onsubmit="event.preventDefault();logged=true;go('home')"><label class="field">帳號<input type="email" value="demo@linkage.tw" autocomplete="username"></label><label class="field">密碼<input type="password" value="demodemo" autocomplete="current-password"></label>${btn('登入 Demo',"logged=true;go('home')")}</form><div class="lock">🔒 本系統僅供授權之照護／服務人員使用</div><div class="login-foot">本 Prototype 所有個案、人物與紀錄皆為虛構示範資料。<br>Demo 登入無須驗證帳號密碼。</div></div></section></div>`}
function logout(){logged=false;route='home';modal='';render();window.scrollTo(0,0)}
function shell(content){const nav=[['home','首頁'],['cases','個案管理'],['resources','活動資源'],['analytics','統計分析'],['settings','設定']];const active=['case','result','newRecord','feedback','feedbackDetail','success'].includes(route)?'cases':route;return `<aside class="sidebar">${brand()}<small style="padding:8px 12px">讓每一次接觸，都累積成理解。</small><nav class="nav">${nav.map(([n,l])=>`<button class="${active===n?'active':''}" onclick="go('${n}')">${icon(n==='analytics'?'analytics':n)}${l}</button>`).join('')}</nav><div class="sidebottom">🔒 機構內部系統<br><small>僅限授權人員使用</small><div class="space">${badge('PROTOTYPE · 示範資料')}</div></div></aside><header class="topbar"><button class="mobile-menu" aria-label="開啟導覽" onclick="$('.sidebar').classList.toggle('open')">☰</button><span class="topdate">○○長照服務單位 <span style="padding:0 12px;color:#d9d3e3">／</span> 服務工作平台</span><div class="user">${badge('已登入','green')}<div class="avatar">林</div><div><p><b>林書含</b>　物理治療師</p><small>○○長照服務單位</small></div><button class="logout-btn" onclick="logout()" aria-label="登出 Demo">登出</button></div></header><main>${content}<footer class="footer">本 Prototype 所有個案、人物與紀錄皆為虛構示範資料。<br>LinkAge · 讓每一次接觸，都累積成對一個人的理解。</footer></main>${modal?renderModal():''}`}
function home(){return `${header('首頁','每一份關心，都值得被記住。')}<div class="welcome"><div><h2>書含，今天也一起讓陪伴更有方向。</h2><p>有 ${followups.length} 位長者在近期等候追蹤，從上一次的對話開始吧。</p></div><div class="dateblock">2026 年 10 月 5 日<br>星期一</div></div>${stats(['追蹤個案','7 天內待追蹤','本月成功參與','待確認事項'],[cases.length,followups.length,participations.length,pendingTasks.length],true)}<div class="grid two gap"><section class="card"><div class="row between section-head"><h2>近期需關注</h2><button class="textbtn" onclick="go('cases')">查看全部</button></div>${[['王伯伯','2 天未確認下次活動時間','待追蹤','orange'],['林奶奶','近期外出頻率下降','待確認','pink'],['陳伯伯','尚無後續接觸紀錄','待聯繫','blue']].map((a,i)=>`<div class="row between focus-row"><div class="row"><div class="avatar">${a[0][0]}</div><div><div class="row"><b>${a[0]}</b>${badge(a[2],a[3])}</div><p>${a[1]}</p></div></div><button class="textbtn" onclick="openCase(${i})">查看個案</button></div>`).join('')}</section><section class="card"><span class="badge">關於 LinkAge</span><h2 class="space">LinkAge 在做什麼？</h2><p class="muted space" style="font-size:14px">把分散的接觸紀錄整理成可追蹤的生活脈絡，協助工作人員辨識參與阻礙、媒合社區資源，並記錄實際參與結果。</p><div class="process">${['接觸紀錄','AI 整理','資源媒合','後續追蹤'].map((s,i)=>`<div class="step"><b>${['☷','✧','♧','✓'][i]}</b><span>${s}</span></div>`).join('')}</div><div class="callout">「我們明明和這個人接觸過很多次，<br>這些接觸有沒有真的讓我們更理解他？」</div></section></div><div class="card gap row between"><div><h3>從王伯伯的故事，開始一次完整的服務流程</h3><p class="small">接觸 → 理解 → 行動 → 參與 → 回饋</p></div>${btn('查看王伯伯',"openCase(0)",'light')}</div>`}
function caseList(){return `${header('個案管理','依最後接觸時間快速掌握待處理事項。',btn('＋ 新增個案',"modal='newCase';render()"))}<div class="lock">🔒 以下僅顯示目前帳號具有服務／查看權限之個案。</div><div class="row between space"><input class="search" aria-label="搜尋個案" placeholder="搜尋姓名、關鍵字……" value="${esc(search)}" oninput="search=this.value;updateCaseRows()"><small>共 ${cases.length} 位服務個案</small></div><div class="filters">${['全部','近 7 天','8–14 天','15–30 天','超過 30 天'].map((s,i)=>`<button class="filter ${caseFilter===s?'active':''}" onclick="caseFilter='${s}';render()">${s}（${i===0?cases.length:cases.filter(c=>c[3]!==null&&(i===1?c[3]<=7:i===2?c[3]>=8&&c[3]<=14:i===3?c[3]>=15&&c[3]<=30:c[3]>30)).length}）</button>`).join('')}</div><div class="card tablecard"><table><thead><tr><th>姓名</th><th>年齡</th><th>最後接觸</th><th>距今天數</th><th>待處理事項</th><th>操作</th></tr></thead><tbody id="caseRows">${caseRows()}</tbody></table></div>`}
function caseRows(){const rows=cases.map((c,i)=>({c,i})).filter(({c})=>c.join(' ').includes(search)&& (caseFilter==='全部'||(caseFilter==='近 7 天'?c[3]!==null&&c[3]<=7:caseFilter==='8–14 天'?c[3]>=8&&c[3]<=14:caseFilter==='15–30 天'?c[3]>=15&&c[3]<=30:c[3]>30)));return rows.length?rows.map(({c,i})=>`<tr class="clickrow" tabindex="0" onclick="openCase(${i})" onkeydown="if(event.key==='Enter')openCase(${i})"><td><div class="namecell"><span class="avatar">${esc(c[0][0])}</span>${esc(c[0])}</div></td><td>${c[1]} 歲</td><td><button class="textbtn" onclick="event.stopPropagation();editCaseFromList(${i})">${c[2]||'尚未接觸'}</button></td><td><button onclick="event.stopPropagation();editCaseFromList(${i})" aria-label="編輯距今天數">${c[3]===null?badge('—'):badge(c[3]+' 天',c[3]>14?'orange':'green')}</button></td><td><button class="textbtn" onclick="event.stopPropagation();editCaseFromList(${i})">${esc(c[4])}</button></td><td><button class="textbtn" onclick="event.stopPropagation();editCaseFromList(${i})">編輯</button><button class="textbtn" onclick="event.stopPropagation();openCase(${i})">查看</button></td></tr>`).join(''):'<tr><td colspan="6" class="empty">沒有符合條件的個案</td></tr>'}
function updateCaseRows(){$('#caseRows').innerHTML=caseRows()}
function profile(){return `<div class="profile"><button class="profile-back" aria-label="返回個案列表" title="返回個案列表" onclick="go('cases')">‹</button><div class="avatar">${esc(cname()[0])}</div><div><h1>${esc(cname())} <small style="font-weight:400">${cases[selectedCase][1]} 歲・${caseGenders[selectedCase]||'未填寫'}</small></h1><div class="row space" style="margin-top:7px">${selectedCase===0?badge('獨居')+badge('可自行步行','green')+badge('有慢性病','blue'):badge(records.length?'已有接觸紀錄':'待建立生活脈絡','blue')}</div></div><div class="profilemeta">個案編號 ${caseCode()}<br>初次接觸 ${selectedCase===0?'2026/08/10':(records.at(-1)?.date||'尚無接觸紀錄')}</div></div><div class="tabs">${[['overview','個案首頁'],['timeline','歷次接觸'],['trends','參與趨勢'],['matching','資源媒合'],['files','檔案資料']].map(([t,l])=>`<button class="${caseTab===t?'active':''}" onclick="tab('${t}')">${l}</button>`).join('')}</div>`}
function casePage(){const names={overview:'個案首頁',timeline:'歷次接觸',trends:'參與趨勢',matching:'資源媒合',files:'檔案資料'};return (fromStat?`<div class="crumb"><button onclick="fromStat=false;go('statDetail')">返回${statTitles[statKind]}明細</button></div>`:'')+crumb([[names[caseTab]]])+profile()+(caseTab==='overview'?caseSummary():'')+({overview:()=>selectedCase===0?overview():otherCase(),timeline,trends:()=>selectedCase===0?trends():emptyTrends(),matching,files:()=>selectedCase===0?files():otherFiles()}[caseTab])()}
function overview(){return `<div class="grid two"><section class="card"><h2>基本資料</h2><dl class="details"><dt>居住地</dt><dd>臺中市西區</dd><dt>聯絡方式</dt><dd>04-2XXX-XXXX</dd><dt>主要照顧者</dt><dd>女兒（白天工作）</dd><dt>就醫狀況</dt><dd>固定回診</dd></dl></section>${[['生活脈絡與興趣','green',['以前常去公園下棋','喜歡與鄰居聊天','重視不麻煩家人','朋友退休後較少外出']],['近期變化','pink',['外出頻率下降','近期曾因膝部不適減少活動','願意嘗試熟悉類型的社區活動']],['可能參與阻礙','orange',['對陌生活動有些擔心','缺少熟悉的同行者','交通便利性會影響意願','膝部不適可能降低外出意願']]].map(([t,c,items])=>`<section class="card"><h2><span class="badge ${c}">✧</span> ${t}</h2><ul>${items.map(i=>`<li>${i}</li>`).join('')}</ul></section>`).join('')}</div><div class="callout gap">依目前工作紀錄整理，以上為生活資訊與待確認因素，不作醫療診斷。重要資訊仍需與長者共同確認。</div><div class="row between gap"><p class="small">最後更新：2026/10/03 · 林書含</p>${btn('查看歷次接觸',"tab('timeline')")}</div>`}
function otherCase(){return `<div class="grid two"><section class="card"><h2>${esc(cname())}的服務摘要</h2><dl class="details"><dt>個案編號</dt><dd>${caseCode()}</dd><dt>接觸紀錄</dt><dd>${records.length} 筆</dd></dl><div class="space">${btn('新增接觸紀錄',"go('newRecord')")}</div></section><section class="card"><h2>生活脈絡與參與條件</h2>${records.length?`<p class="muted space">${esc(records[0].summary)}</p><p class="small space">依最近一筆接觸紀錄呈現，重要資訊仍待工作人員確認。</p>`:'<p class="muted space">目前尚未記錄興趣、交通需求與可參與時段。</p><p class="small space">可先新增一次接觸，或瀏覽資源後與長者一起確認。</p>'}<div class="space">${btn('為'+esc(cname())+'查看資源',"tab('matching')",'light')}</div></section></div>`}
function timeline(){return `${header('歷次接觸','把每次對話與參與，串成持續的理解。',btn('＋ 新增接觸紀錄',"go('newRecord')"))}<div class="timeline">${records.length?'':'<div class="card empty">尚無接觸紀錄，點擊「新增接觸紀錄」開始記下第一次交流。</div>'}${records.map((r,i)=>`<article class="event"><div class="date">${esc(r.date)}</div><div class="card"><div class="row between"><div><h3>${esc(r.source)}</h3><small>${esc(r.person)}</small></div>${badge(r.status,r.status.includes('已參與')?'green':r.status==='考慮參與'?'orange':'blue')}</div><p>${esc(r.summary)}</p><div class="row between"><small>${r.feedback?'參與結果 · 已寫入個案紀錄':'接觸紀錄 · 依服務權限開放'}</small><button class="textbtn" onclick="viewRecord(${i})">查看</button></div></div></article>`).join('')}</div>`}
const aiSections=[['本次新增資訊',['過去有下棋習慣，且對此有正向感受','近期膝部不適，外出活動減少','對再次參與活動有意願','星期三較不方便']],['與前次相比的變化',['從「有興趣先看看」進一步表達願意再次參與','新增時間偏好','新增距離偏好']],['可能參與阻礙',['膝部不適可能影響外出','活動距離過遠可能降低參與意願','陌生環境可能增加參與門檻']],['低風險協助因子',['熟悉的下棋活動可降低陌生感','鄰近、交通方便的據點較適合優先詢問','若有熟悉的人同行，可能增加首次參與意願']],['下次可確認事項',['確認近期膝部不適是否仍影響外出','確認星期三以外可參與的時段','確認可接受的交通方式與距離','確認是否希望有人陪同第一次參與']]];
function result(){const r=records[recordIndex];let sections=selectedCase===0&&r.text===baseText?aiSections:r.custom?[[ '本次新增資訊',[r.summary,'以上為原始文字摘要，待工作人員確認。'] ],['與前次相比的變化',['待工作人員核對原始文字與前次紀錄']],['可能參與阻礙',['請依本次文字確認影響參與的因素']],['低風險協助因子',['可先詢問熟悉活動與陪同意願']],['下次可確認事項',['確認本次文字中的重要資訊','確認參與意願、交通與可配合時段']]]: [['本次新增資訊',[r.summary]],['與前次相比的變化',['依本次紀錄保留新的生活資訊，待工作人員確認']],['可能參與阻礙',['陌生環境與缺少同行者可能影響參與意願']],['低風險協助因子',['熟悉的活動與熟悉的人同行可優先詢問']],['下次可確認事項',['確認活動意願','確認交通方式與陪同需求']]];return `${crumb([['歷次接觸',"tab('timeline')"],[esc(r.date)]])}${header('AI 整理結果')}<div class="row"><div class="avatar">${esc(cname()[0])}</div><div><b>${esc(cname())}</b>　${badge(r.source)}<p class="small">${esc(r.date)}　紀錄者：${esc(r.person)}</p></div></div><div class="segmented"><button class="${resultTab==='ai'?'active':''}" onclick="resultTab='ai';render()">AI 整理紀錄</button><button class="${resultTab==='raw'?'active':''}" onclick="resultTab='raw';render()">原始逐字稿</button></div>${resultTab==='raw'?`<div class="card"><div class="restricted"><b>🔒 受限資料 · 依角色權限開放</b><p class="small space">正式系統中，原始逐字稿將依角色與服務權限限制存取。</p></div><p class="transcript">${esc(r.text)}</p></div>`:`<div class="callout" style="margin-bottom:20px">✧ 依目前紀錄整理 · Mock AI Result<br>AI 僅協助整理與提示，內容待工作人員確認，不取代專業判斷。</div><div class="grid two">${sections.map(([t,items],i)=>`<section class="card ai-card" style="${i===4?'grid-column:1/-1':''}"><span class="ai-num">${i+1}</span><div><h2>${t}</h2><ul>${items.map(s=>`<li>${s}</li>`).join('')}</ul></div></section>`).join('')}</div>`}<div class="row between gap actions">${btn('返回歷次接觸',"tab('timeline')",'secondary')}${btn('前往資源媒合 →',"tab('matching')")}</div>`}
function newRecord(){return `${crumb([['歷次接觸',"tab('timeline')"],['新增接觸紀錄']])}${header('新增接觸紀錄',esc(cname())+' · '+caseCode())}<form class="card formwidth" onsubmit="saveRecord(event)"><div class="formgrid"><label class="field">日期<input id="recDate" type="date" value="${selectedCase===0?'2026-10-03':'2026-10-05'}" required></label><label class="field">紀錄者<input id="recPerson" value="林書含" required></label><label class="field">專業身分<select id="recRole">${['物理治療師','社工','護理師','照顧服務員','志工','其他'].map(s=>`<option>${s}</option>`).join('')}</select></label></div><label class="field gap">紀錄來源<select id="recSource">${['現場訪談','電話訪談','其他'].map(s=>`<option>${s}</option>`).join('')}</select></label><div class="field gap">輸入方式</div><div class="segmented"><button type="button" class="active" onclick="showInputMode('文字',this)">貼上文字</button><button type="button" onclick="showInputMode('檔案',this)">上傳檔案／逐字稿</button><button type="button" onclick="showInputMode('語音',this)">語音轉文字</button></div><div id="inputExtra"></div><label class="field">接觸內容<textarea id="recText" required placeholder="記錄這次對話：生活近況、興趣、外出意願、方便時段與需要的協助……">${selectedCase===0?baseText:''}</textarea></label><div class="callout gap">AI 整理僅提供資訊整理與追蹤提示。本 Prototype 使用預設示範結果。</div><div class="row between gap">${btn('取消',"tab('timeline')",'secondary')}<button class="btn" type="submit">儲存並進行 AI 整理</button></div></form>`}
function showInputMode(mode,b){b.parentNode.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#inputExtra').innerHTML=mode==='檔案'?'<label class="field" style="margin-bottom:18px">選擇文字逐字稿（.txt）<input type="file" accept=".txt,text/plain" onchange="readFile(this)"></label>':mode==='語音'?'<div class="callout" style="margin-bottom:18px">Demo 模擬語音轉文字，不使用麥克風。 <button type="button" class="textbtn" onclick="document.querySelector(\'#recText\').value=selectedCase===0?baseText:\'今天聊到喜歡與鄰居交流，希望先了解附近有哪些活動，交通與陪同需求還需要再確認。\';toast(\'已載入示範語音文字\')">載入示範語音文字</button></div>':''}
function readFile(input){let f=input.files[0];if(f)f.text().then(t=>{$('#recText').value=t;toast('已載入文字逐字稿')})}
function saveRecord(e){e.preventDefault();const text=$('#recText').value;records.unshift({date:$('#recDate').value.replaceAll('-','/'),person:$('#recPerson').value+'（'+$('#recRole').value+'）',source:$('#recSource').value,text,summary:text.length>65?text.slice(0,65)+'…':text,status:'待確認',custom:selectedCase!==0||text.trim()!==baseText});cases[selectedCase][2]=records[0].date;cases[selectedCase][3]=0;recordIndex=0;resultTab='ai';saveDemo();go('result');toast('接觸紀錄已儲存，已呈現示範整理结果')}
function filterUI(context){return `<div class="filters">${[['type','活動類型',['棋藝','共餐','健走','手作','歌唱']],['area','地區',['西區','南區','北區']],['day','時間',['週二','週三','週五','週六']],['traffic','交通方式',['步行','公車','接送']]].map(([k,l,opts])=>`<select aria-label="${l}" onchange="filters.${k}=this.value;render()"><option value="">${l} · 全部</option>${opts.map(v=>`<option ${filters[k]===v?'selected':''}>${v}</option>`).join('')}</select>`).join('')}${context?`<label class="toggle"><input type="checkbox" ${onlySuggested?'checked':''} onchange="onlySuggested=this.checked;render()">僅顯示建議</label>`:''}</div>`}
function matching(){const suggestions=suggestedResources();return `${header('適合'+esc(cname())+'的活動／資源','依目前紀錄中的興趣、參與條件與待確認因素，提供工作人員優先查看的資源。')}${selectedCase===0?`<div class="row">${badge('興趣：下棋')}${badge('時間：避開星期三','blue')}${badge('距離：希望不要太遠','green')}</div>`:`<div class="callout">${suggestions.length?'依接觸文字中的活動關鍵字提供示範篩選；適合程度、時間與交通仍待確認。':'目前興趣與參與條件尚待確認。可先瀏覽全部資源，再與'+esc(cname())+'討論。'}</div>`}${filterUI(true)}${resourceList(true)}<div class="callout gap">以上供工作人員進一步確認。最後決策由工作人員與長者共同討論。</div>`}
function resourcePage(){return `${header('活動資源','瀏覽社區資源庫，為下一次連結準備更多可能。')}<input class="search" placeholder="搜尋活動、據點……" aria-label="搜尋活動" value="${esc(resourceSearch)}" oninput="resourceSearch=this.value;document.querySelector('#resourceList').innerHTML=resourceList(false)">${filterUI(false)}<div id="resourceList">${resourceList(false)}</div>`}
function resourceList(context){let list=resources.map((r,i)=>({r,i})).filter(({r,i})=>(!context||!onlySuggested||suggestedResources().includes(i))&&(!resourceSearch||context||r.name.includes(resourceSearch))&&Object.entries(filters).every(([k,v])=>!v||r[k].includes(v)));return list.length?`<div class="grid">${list.map(({r,i})=>`<article class="card resource"><div><div class="row between"><span class="resource-icon">${r.symbol}</span>${context?badge(isTracked(i)?'追蹤中':suggestedResources().includes(i)?'建議優先查看':'待確認適合度',isTracked(i)?'green':''):badge('社區資源','blue')}</div><h2>${r.name}</h2><div class="row">${r.tags.map(t=>badge(t)).join('')}</div><dl class="details"><dt>地點</dt><dd>${r.place}</dd><dt>時間</dt><dd>${r.day} ${r.time}</dd><dt>交通</dt><dd>${r.traffic}</dd><dt>費用</dt><dd>免費</dd></dl><div class="resource-actions">${btn('查看詳情',`selectedResource=${i};modal='resource';render()`,'secondary')}${context?(isTracked(i)?btn('新增參與回饋',`selectedResource=${i};go('feedback')`):btn('加入追蹤',`selectedResource=${i};modal='track';render()`)):''}</div></div><div class="resource-side"><h3>${context&&selectedCase===0&&i===0?'為什麼建議優先查看？':'資源介紹'}</h3>${context&&selectedCase===0&&i===0?'<ul><li>✓ 與過去下棋興趣相符</li><li>✓ 時間避開星期三</li><li>✓ 距離較近</li><li>✓ 有其他長者共同參與</li></ul>':`<p class="muted space" style="font-size:14px">${r.desc}</p>`}<div class="callout gap">${context?'可能符合目前條件，參與意願與安排仍待確認。':'服務人員可依個案興趣與條件進一步確認。'}</div></div></article>`).join('')}</div>`:'<div class="card empty">沒有符合條件的活動，請調整篩選。</div>'}
function feedback(){return `${crumb([['資源媒合',"tab('matching')"],[resources[selectedResource].short],['參與回饋']])}${header('新增參與回饋',esc(cname())+' · '+resources[selectedResource].name)}<form class="card formwidth" onsubmit="saveFeedback(event)"><label class="field">參與日期<input type="date" id="fbDate" value="${selectedCase===0?'2026-10-03':'2026-10-05'}" required></label><div class="field gap">是否參與<div class="radio"><label><input type="radio" name="attended" value="yes" checked> 有參與</label><label><input type="radio" name="attended" value="no"> 未參與</label></div></div><label class="field gap">參與後感受<textarea id="fbFeeling" required placeholder="記下參與後的感受、是否認識新朋友，以及下次希望如何安排……">${selectedCase===0&&selectedResource===0?'覺得很開心，認識了隔壁桌的陳先生，想再去。':''}</textarea></label><div class="field gap">是否願意繼續<div class="radio">${['願意','暫不確定','不願意'].map((v,i)=>`<label><input type="radio" name="continue" value="${v}" ${i===0?'checked':''}> ${v}</label>`).join('')}</div></div><label class="field gap">主要原因<textarea id="fbReason" placeholder="參與或未參與的原因、希望獲得的協助……">${selectedCase===0&&selectedResource===0?'和其他人一起下棋很開心，但回程要走一小段路。':''}</textarea></label><div class="row between gap">${btn('返回資源媒合',"tab('matching')",'secondary')}<button class="btn" type="submit">儲存參與回饋</button></div></form>`}
function saveFeedback(e){e.preventDefault();const attended=$('input[name="attended"]:checked').value==='yes',feeling=$('#fbFeeling').value,willing=$('input[name="continue"]:checked').value,reason=$('#fbReason').value;records.unshift({date:$('#fbDate').value.replaceAll('-','/'),person:'林書含（物理治療師）',source:resources[selectedResource].short+'參與回饋',summary:attended&&feeling==='覺得很開心，認識了隔壁桌的陳先生，想再去。'&&willing==='願意'?'覺得很開心，認識了新的棋友，表示願意再次參與。':(attended?'已參與。':'未參與。')+feeling+' 繼續參與意願：'+willing,status:attended?'已參與':'未參與',feedback:true,feeling,willing,reason});if(attended)participations.unshift({caseId:selectedCase,date:records[0].date,activity:resources[selectedResource].short,feeling});saveDemo();go('success')}
function success(){return `${crumb([['資源媒合',"tab('matching')"],['參與回饋']])}<div class="card success"><div class="success-icon">✓</div><h1>參與結果已加入${esc(cname())}的歷次紀錄。</h1><p class="muted space">這次參與，會成為下一次理解${esc(cname())}的新資訊。</p><div class="gap">${btn('返回'+esc(cname())+'歷次接觸',"tab('timeline')")}</div></div>`}
function feedbackDetail(){const r=records[recordIndex];return `${crumb([['歷次接觸',"tab('timeline')"],[r.date]])}${header(r.source,esc(cname())+' · '+r.date)}<div class="card">${badge(r.status,'green')}<dl class="details"><dt>參與後感受</dt><dd>${esc(r.feeling)}</dd><dt>繼續參與意願</dt><dd>${esc(r.willing)}</dd><dt>主要原因</dt><dd>${esc(r.reason)}</dd></dl><div class="callout gap">下次可確認：回程交通安排，以及再次參與的時間。</div></div><div class="gap">${btn('返回歷次接觸',"tab('timeline')",'secondary')}</div>`}
function bars(labels,values,max=20){return `<div class="chart">${labels.map((l,i)=>`<div class="bar" style="height:${values[i]/max*85}%"><span>${values[i]}</span><label>${l}</label></div>`).join('')}</div>`}
function trends(){return `<div class="grid two"><section class="card"><h2>近幾個月外出／社會參與情形</h2><p class="small">依服務接觸紀錄整理的相對變化</p><div class="chart">${[['7 月','較頻繁',85],['8 月','普通',60],['9 月','下降',30],['10 月','開始恢復',65]].map(([m,s,h])=>`<div class="bar" style="height:${h}%"><span>${s}</span><label>${m}</label></div>`).join('')}</div></section><section class="card"><h2>從紀錄中看見的轉變</h2><ul><li>7 月：仍會外出與鄰居交流</li><li>8 月：外出情形較為普通</li><li>9 月：提到膝部不適，較少出門</li><li>10 月：參與棋藝活動，表達再次參與意願</li></ul><div class="callout gap">本區呈現服務紀錄中的生活與參與變化，不作醫療診斷。</div></section></div>`}
function files(){return `<div class="card"><h2>檔案資料</h2><div class="restricted gap">🔒 受限資料 · 依角色與服務權限開放</div><div class="settings-row"><div><h3>基本資料摘要</h3><p>個案編號 A001 · 初次接觸 2026/08/10</p></div>${btn('查看',"modal='file';render()",'secondary')}</div><div class="settings-row"><div><h3>2026/10/03 原始訪談紀錄</h3><p>僅限具備原始紀錄存取權限的人員</p></div>${btn('查看',"recordIndex=records.findIndex(r=>r.source==='現場訪談'&&r.date==='2026/10/03');resultTab='raw';go('result')",'secondary')}</div></div>`}
function analytics(){return `${header('統計分析','機構服務流程與社會參與結果 · 2026 年 10 月示範資料')}${stats(['本月接觸個案數','成功媒合資源數','實際參與人數','持續參與人數'],[12,10,8,6])}<div class="grid two gap"><section class="card"><h2>從媒合到持續參與</h2><p class="small">讓服務結果持續被看見</p>${bars(['已媒合','有意願','已參與','持續參與'],[10,9,8,6],12)}</section><section class="card"><h2>常見參與阻礙</h2><p class="small">依服務紀錄整理，可作為後續確認方向</p>${[['交通',7],['身體不適',5],['缺乏陪伴',4],['活動不熟悉',3],['時間不合',2]].map(([s,n])=>`<div class="obstacle"><span>${s}</span><div class="trackbar"><div style="width:${n/8*100}%"></div></div><span>${n} 件</span></div>`).join('')}</section></div><div class="card gap"><h2>從首次媒合 → 實際參與</h2><div class="process">${[['10','首次媒合'],['9','表達意願'],['8','實際參與'],['6','持續參與']].map(([n,s])=>`<div class="step"><b>${n}</b><span>${s}</span></div>`).join('')}</div><div class="callout">每一次媒合之後，記錄是否真的參與與參與感受，才能知道下一步需要什麼支持。</div></div>`}
function settings(){return `${header('設定','讓服務協作與資料使用保有清楚的邊界。')}<div class="grid two"><div class="card"><h2>機構與使用者</h2><dl class="details"><dt>機構名稱</dt><dd>○○長照服務單位</dd><dt>使用者</dt><dd>林書含</dd><dt>專業身分</dt><dd>物理治療師</dd></dl><div class="gap">${btn('登出 Demo',"logout()",'secondary')}</div></div><div class="card"><h2>通知設定</h2>${[['追蹤事項提醒','提醒近期待確認與未完成事項'],['參與結果提醒','收到個案新的參與回饋時提示']].map(([s,d],i)=>`<div class="settings-row"><div><h3>${s}</h3><p>${d}</p></div><input class="switch" type="checkbox" aria-label="${s}" ${prefs[i]?'checked':''} onchange="prefs[${i}]=this.checked;toast('通知設定已更新')"></div>`).join('')}</div><div class="card"><h2>AI 整理設定</h2><div class="settings-row"><div><h3>整理後保留人工確認</h3><p>重要資訊須經工作人員確認後才寫入個案紀錄。</p></div>${badge('必要流程')}</div><div class="callout gap">AI 整理內容僅作為工作人員資訊整理與追蹤輔助，不取代專業判斷。</div></div><div class="card"><h2>資料與隱私設定</h2><div class="restricted gap">🔒 僅限授權人員 · 依角色權限開放</div><p class="muted" style="font-size:14px">正式系統將依所屬機構、服務關係及角色權限限制個案資料存取。</p><p class="small space">登入身分 → 所屬機構 → 角色權限 → 授權個案</p></div></div>`}
let prefs=[true,true];
function renderModal(){const r=resources[selectedResource];let body=modal==='editSummary'?editSummaryForm():modal==='track'?`<h2>加入${esc(cname())}的追蹤項目</h2><p class="muted space">${r.name}</p><h3 class="gap">待確認</h3><ul><li>是否願意參加</li><li>交通安排</li><li>是否需要首次陪同</li></ul><div class="row between gap">${btn('取消',"modal='';render()",'secondary')}${btn('建立參與追蹤',"createTracking()")}</div>`:modal==='resource'?`<h2>${r.name}</h2><p class="muted space">${r.desc}</p><dl class="details"><dt>地點</dt><dd>${r.place}</dd><dt>時間</dt><dd>${r.day} ${r.time}</dd><dt>費用</dt><dd>免費</dd><dt>聯絡方式</dt><dd>04-2XXX-XXXX（示範）</dd></dl><div class="callout gap">參與前，請進一步確認名額、交通安排與首次陪同需求。</div><div class="gap">${btn('關閉',"modal='';render()",'secondary')}</div>`:modal==='newCase'?`<h2>新增示範個案</h2><form onsubmit="addCase(event)"><label class="field">姓名<input id="caseName" required placeholder="請輸入示範姓名"></label><label class="field">年齡<input id="caseAge" type="number" min="60" max="110" value="78" required></label><label class="field">性別<select id="caseGender"><option>男性</option><option>女性</option><option>未填寫</option></select></label><label class="field">最後接觸日期（可留空）<input id="editContactDate" type="date" max="2026-10-05" onchange="syncContactDays()"></label><label class="field">距今天數<input id="editContactDays" type="number" min="0" step="1" placeholder="尚未接觸" oninput="syncContactDate()"></label><label class="field">待處理事項<select id="caseTask" required onchange="toggleOtherTask(this.value)">${['安排初次訪視','安排電話關懷','協助安排就醫／回診','確認活動參與意願','確認交通／接送安排','安排首次活動陪同','追蹤活動參與回饋','確認居家支持需求','其他'].map(t=>`<option>${t}</option>`).join('')}</select></label><label class="field" id="otherTaskField" hidden>其他待處理事項<input id="caseTaskOther" placeholder="請描述需要處理的事項" maxlength="160" disabled></label><div class="row between gap">${btn('取消',"modal='';render()",'secondary')}<button class="btn" type="submit">新增個案</button></div></form>`:'<h2>王伯伯基本資料摘要</h2><dl class="details"><dt>個案編號</dt><dd>A001</dd><dt>居住地</dt><dd>臺中市西區</dd><dt>照顧者</dt><dd>女兒（白天工作）</dd><dt>初次接觸</dt><dd>2026/08/10</dd></dl><div class="gap">'+btn('關閉',"modal='';render()",'secondary')+'</div>';return `<div class="modal-bg" onclick="if(event.target===this){modal='';render()}"><section class="card modal" role="dialog" aria-modal="true" aria-label="${modal==='newCase'?'新增個案':'活動與個案資料'}">${body}</section></div>`}
function toggleOtherTask(value){const other=value==='其他';$('#otherTaskField').hidden=!other;$('#caseTaskOther').disabled=!other;$('#caseTaskOther').required=other;if(other)$('#caseTaskOther').focus()}
function addCase(e){e.preventDefault();const task=$('#caseTask').value==='其他'?$('#caseTaskOther').value.trim():$('#caseTask').value;if(!task){$('#caseTaskOther').setCustomValidity('請填寫其他待處理事項');$('#caseTaskOther').reportValidity();$('#caseTaskOther').oninput=function(){this.setCustomValidity('')};return}const contact=$('#editContactDate').value;cases.push([$('#caseName').value.trim(),Number($('#caseAge').value),contact?contact.replaceAll('-','/'):'',contact?contactDays(contact):null,task]);caseGenders.push($('#caseGender').value);caseRecords[cases.length-1]=[];pendingTasks.push({caseId:cases.length-1,task,note:'新增個案待處理事項，請於下次接觸確認。'});saveDemo();modal='';search='';caseFilter='全部';render();toast('已新增示範個案')}

let statKind=0,fromStat=false;
const statTitles=['追蹤個案','7 天內待追蹤','本月成功參與','待確認事項'];
const followups=[{caseId:0,due:'2026/10/06',task:'確認下次棋藝活動時間'},{caseId:1,due:'2026/10/07',task:'確認參與活動的交通方式'},{caseId:5,due:'2026/10/08',task:'確認首次參與的陪同人選'},{caseId:6,due:'2026/10/09',task:'電話詢問社區共餐意願'}];
const pendingTasks=[{caseId:0,task:'確認下次活動時間',note:'詢問星期三以外方便的時段。'},{caseId:1,task:'確認交通方式',note:'了解是否需要接送或熟悉的人同行。'},{caseId:2,task:'補上後續接觸紀錄',note:'再次聯繫，記下近期生活與參與意願。'},{caseId:3,task:'評估居家支持需求',note:'詢問目前生活中希望獲得的協助。'},{caseId:4,task:'安排再次訪視',note:'確認方便聯繫與訪視的時間。'},{caseId:5,task:'確認陪同人選',note:'詢問是否希望有人陪同首次參與。'}];
const participations=[{caseId:0,date:'2026/10/03',activity:'長者棋藝活動',feeling:'認識新的棋友，表示願意再次參與。'},{caseId:1,date:'2026/10/02',activity:'社區共餐',feeling:'與鄰居一起用餐，願意再來。'},{caseId:5,date:'2026/10/03',activity:'手作課程',feeling:'在志工陪同下完成作品，覺得有成就感。'},{caseId:6,date:'2026/10/01',activity:'社區共餐',feeling:'喜歡和其他人聊天，下次時間待確認。'},{caseId:7,date:'2026/10/03',activity:'手作課程',feeling:'喜歡手作主題，願意嘗試下一次課程。'},{caseId:8,date:'2026/10/02',activity:'長者棋藝活動',feeling:'遇到熟悉的鄰居，希望持續參與。'},{caseId:9,date:'2026/10/01',activity:'社區歌唱活動',feeling:'喜歡熟悉的歌曲，回程交通待確認。'},{caseId:10,date:'2026/10/02',activity:'公園健走團',feeling:'喜歡與同伴交流，希望先確認下次路線。'}];
function openStat(kind){statKind=kind;fromStat=false;search='';caseFilter='全部';go('statDetail')}
function openStatCase(id){fromStat=true;openCase(id)}
function statPerson(id){return `<div class="namecell"><span class="avatar">${esc(cases[id][0][0])}</span>${esc(cases[id][0])}</div>`}
function statDetail(){const title=statTitles[statKind],count=[cases.length,followups.length,participations.length,pendingTasks.length][statKind],descriptions=['目前帳號具有服務／查看權限的個案。','預計於 2026/10/05–2026/10/11 聯繫或追蹤的長者。','2026 年 10 月已記錄的實際參與結果。','下一次接觸時，可以直接確認的工作事項。'];let content='';
if(statKind===0){content=`<div class="card tablecard"><table><thead><tr><th>姓名</th><th>年齡</th><th>最後接觸</th><th>待處理事項</th><th>操作</th></tr></thead><tbody>${cases.map((c,i)=>`<tr><td>${statPerson(i)}</td><td>${c[1]} 歲</td><td>${c[2]||'尚未接觸'}</td><td>${esc(c[4])}</td><td>${btn('查看個案',`openStatCase(${i})`,'light')}</td></tr>`).join('')}</tbody></table></div>`}
else{const items=statKind===1?followups:statKind===2?participations:pendingTasks;content=`<div class="grid two">${items.map((item,i)=>`<article class="card stat-item"><div class="row between">${statPerson(item.caseId)}${badge(statKind===1?'待追蹤':statKind===2?'已參與':'待確認',statKind===2?'green':'orange')}</div><h2 class="space">${esc(item.activity||item.task)}</h2>${statKind===1?`<p class="small space">預計追蹤日期：${item.due}</p><p class="small">最後接觸：${cases[item.caseId][2]}</p>`:statKind===2?`<p class="small space">參與日期：${esc(item.date)}</p><p class="muted space">${esc(item.feeling)}</p>`:`<p class="muted space">${esc(item.note)}</p>`}<div class="space">${btn('查看個案',`openStatCase(${item.caseId})`,'light')}</div></article>`).join('')}</div>`}
return `<div class="crumb"><button onclick="go('home')">首頁</button><span>／</span><span>${title}</span></div>${header(title,descriptions[statKind],btn('返回首頁',"go('home')",'secondary'))}<div class="row between" style="margin-bottom:20px"><div class="lock">🔒 僅顯示目前帳號授權查看的示範資料</div>${badge('共 '+count+(statKind<2?' 位':' 筆'))}</div>${content}`}


let caseRecords={0:records},caseTracks={},caseGenders=cases.map(c=>c[0].includes('奶奶')?'女性':'男性');
function caseCode(){return 'A'+String(selectedCase+1).padStart(3,'0')}
function isTracked(resourceId){return (caseTracks[selectedCase]||[]).includes(resourceId)}
function createTracking(){const list=caseTracks[selectedCase]||(caseTracks[selectedCase]=[]);if(!list.includes(selectedResource))list.push(selectedResource);modal='';saveDemo();render();toast('已建立'+cname()+'的活動追蹤')}
function suggestedResources(){if(selectedCase===0)return [0];const text=records.map(r=>r.text||r.summary).join(' ');const keys=[['下棋','棋藝'],['共餐','一起吃飯'],['健走','散步'],['手作'],['唱歌','歌唱']];return keys.map((terms,i)=>terms.some(t=>text.includes(t))?i:-1).filter(i=>i>=0)}
function emptyTrends(){return `<div class="card"><h2>${esc(cname())}的參與趨勢</h2>${records.some(r=>r.feedback)?`<ul>${records.filter(r=>r.feedback).map(r=>`<li>${esc(r.date)} · ${esc(r.source)} · ${esc(r.status)}</li>`).join('')}</ul>`:'<p class="muted space">尚無參與回饋。新增參與結果後，這裡會呈現紀錄中的變化。</p>'}<div class="callout gap">本區呈現服務紀錄中的生活與參與變化，不作醫療診斷。</div></div>`}
function otherFiles(){return `<div class="card"><h2>${esc(cname())}的檔案資料</h2><div class="restricted gap">🔒 受限資料 · 依角色與服務權限開放</div><p class="muted space">目前有 ${records.length} 筆接觸／參與紀錄。原始文字可從歷次接觸逐筆查看。</p><div class="space">${btn('查看歷次接觸',"tab('timeline')",'light')}</div></div>`}
function saveDemo(){try{sessionStorage.setItem('linkage-demo-v2',JSON.stringify({cases,caseRecords,caseTracks,caseGenders,participations,pendingTasks,followups}))}catch(e){}}
try{const saved=JSON.parse(sessionStorage.getItem('linkage-demo-v2')||'null');if(saved?.cases&&saved?.caseRecords){cases=saved.cases;caseRecords=saved.caseRecords;caseTracks=saved.caseTracks||{};caseGenders=saved.caseGenders||caseGenders;participations.splice(0,participations.length,...saved.participations);pendingTasks.splice(0,pendingTasks.length,...saved.pendingTasks);if(saved.followups)followups.splice(0,followups.length,...saved.followups);records=caseRecords[0]||[]}}catch(e){}


const taskOptions=['安排初次訪視','安排電話關懷','協助安排就醫／回診','確認活動參與意願','確認交通／接送安排','安排首次活動陪同','追蹤活動參與回饋','確認居家支持需求'];
function caseSummary(){return `<section class="card" style="margin-bottom:20px"><div class="row between"><h2>服務摘要</h2>${btn('編輯',"modal='editSummary';render()",'secondary')}</div><dl class="details"><dt>最後接觸</dt><dd>${esc(cases[selectedCase][2]||'尚未接觸')}</dd><dt>距今天數</dt><dd>${cases[selectedCase][3]===null?'—':cases[selectedCase][3]+' 天'}</dd><dt>待確認事項</dt><dd>${esc(cases[selectedCase][4])}</dd></dl></section>`}
function editSummaryForm(){const task=cases[selectedCase][4],other=!taskOptions.includes(task);return `<h2>編輯${esc(cname())}的服務摘要</h2><form onsubmit="saveCaseSummary(event)"><label class="field">最後接觸日期<input id="editContactDate" type="date" max="2026-10-05" value="${cases[selectedCase][2].replaceAll('/','-')}" onchange="syncContactDays()"></label><label class="field">距今天數<input id="editContactDays" type="number" min="0" step="1" value="${cases[selectedCase][3]??''}" placeholder="尚未接觸" oninput="syncContactDate()"></label><p class="small space">日期與天數連動，依 Demo 今日 2026/10/05 計算；留空表示尚未接觸。</p><label class="field">待確認事項<select id="caseTask" onchange="toggleOtherTask(this.value)">${[...taskOptions,'其他'].map(t=>`<option ${t===(other?'其他':task)?'selected':''}>${t}</option>`).join('')}</select></label><label class="field" id="otherTaskField" ${other?'':'hidden'}>其他待確認事項<input id="caseTaskOther" value="${other?esc(task):''}" ${other?'required':'disabled'} placeholder="請描述需要處理的事項" maxlength="160"></label><div class="row between gap">${btn('取消',"modal='';render()",'secondary')}<button class="btn" type="submit">儲存修改</button></div></form>`}
function saveCaseSummary(event){event.preventDefault();const task=$('#caseTask').value==='其他'?$('#caseTaskOther').value.trim():$('#caseTask').value;if(!task){$('#caseTaskOther').setCustomValidity('請填寫待確認事項');$('#caseTaskOther').reportValidity();$('#caseTaskOther').oninput=function(){this.setCustomValidity('')};return}const date=$('#editContactDate').value;cases[selectedCase][2]=date.replaceAll('-','/');cases[selectedCase][3]=date?contactDays(date):null;let pending=pendingTasks.find(t=>t.caseId===selectedCase);if(pending){pending.task=task;pending.note='依服務摘要更新，請於下次接觸確認。'}else pendingTasks.push({caseId:selectedCase,task,note:'請於下次接觸確認。'});for(const followup of followups)if(followup.caseId===selectedCase)followup.task=task;cases[selectedCase][4]=task;modal='';saveDemo();render();toast('已更新'+cname()+'的服務摘要')}


function contactDays(date){return Math.max(0,Math.round((Date.UTC(2026,9,5)-Date.parse(date+'T00:00:00Z'))/86400000))}
function syncContactDays(){const date=$('#editContactDate').value;$('#editContactDays').value=date?contactDays(date):''}
function syncContactDate(){const raw=$('#editContactDays').value;if(raw===''){$('#editContactDate').value='';return}const days=Number(raw);if(!Number.isInteger(days)||days<0)return;$('#editContactDate').value=new Date(Date.UTC(2026,9,5)-days*86400000).toISOString().slice(0,10)}
function editCaseFromList(id){selectedCase=id;records=caseRecords[id]||(caseRecords[id]=[]);modal='editSummary';render()}

function render(){$('#app').innerHTML=logged?shell(({home,statDetail,cases:caseList,case:casePage,result,newRecord,resources:resourcePage,feedback,feedbackDetail,success,analytics,settings}[route]||home)()):login();if(modal){requestAnimationFrame(()=>$('.modal button, .modal input')?.focus())}}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal){modal='';render()}});
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'open_linkage_case',description:'開啟王伯伯示範個案與指定頁籤。',inputSchema:{type:'object',properties:{tab:{type:'string',enum:['overview','timeline','trends','matching','files']}},required:['tab'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!['overview','timeline','trends','matching','files'].includes(input.tab))throw new Error('不支援的頁籤');logged=true;openCase(0,input.tab);return {case:'王伯伯',tab:caseTab}}})}catch(e){console.warn('WebMCP unavailable')}}
render();
